---
name: Comment PR with Infra Plan Status
on:
  workflow_call:
    inputs:
      lint:
        required: true
        type: string
      test:
        required: true
        type: string
      build:
        required: true
        type: string
      image-build:
        required: true
        type: string

jobs:
  update-pr-with-golang-build-status:
    runs-on: ubuntu-latest
    steps:
      - name: Update Pull Request
        uses: actions/github-script@v9
        with:
          script: |
            const output = `#### Lint \`${{ inputs.lint }}\`
            #### Test \`${{ inputs.test }}\`
            #### Build \`${{ inputs.build }}\`
            #### Image Build \`${{ inputs.image-build }}\`

            *Pushed by: @${{ github.actor }}*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
